spring:
  application:
    name: discovery-server

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



