logging:
  file:
    name: ${spring.application.name}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] --- [%t] %c : %m%n"
  logback:
    rollingpolicy:
      max-file-size: 2MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0