spring:
  application:
    name: account-service
  config:
    import: configserver:http://localhost:8888

feign:
  circuitbreaker:
    enabled: true


service:
  notification-url: http://localhost:8092/api/v1
  statistic-url: http://localhost:8091/api/v1

resilience4j:
  circuitbreaker:
    instances:
      notification-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      statistic-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5